Parameters:
  CommitMessage:
    Type: String
  EndPoint:
    Type: String
    Default: hello-nghiem
  InfrastructureName:
    Type: String
    Default: nx-vid
  EnvironmentType:
    Description: Specify the Environment type of the stack.
    Type: String
    Default: test
    AllowedValues:
      - dev
      - test
      - prod
    ConstraintDescription: Specify either dev, test or prod.
  S3BucketName:
    Type: String
    Default: my-bucket-bucket

Resources:
  ApiGatewayResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !ImportValue RestApiRootResourceId
      RestApiId: !ImportValue RestApiId
      PathPart: !Ref EndPoint
  ApiGatewayStateResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref ApiGatewayResource
      RestApiId: !ImportValue RestApiId
      PathPart: state
  
Outputs:
  ApiGatewayResource:
    Value: !Ref ApiGatewayResource
    Export:
      Name: ApiGatewayHelloNghiemResource
  ApiGatewayStateResource:
    Value: !Ref ApiGatewayStateResource
    Export:
      Name: ApiGatewayHelloNghiemStateResource