Parameters:
  CommitMessage:
    Type: String
  EndPoint:
    Type: String
    Default: hello-nghiem
  InfrastructureName:
    Type: String
    Default: nx-vid
  EnvironmentType:
    Description: Specify the Environment type of the stack.
    Type: String
    Default: test
    AllowedValues:
      - dev
      - test
      - prod
    ConstraintDescription: Specify either dev, test or prod.
  S3BucketName:
    Type: String
    Default: my-bucket-bucket

Resources:
  # should be in main_template    
  ApiGatewayRequestQueryStringValidator:
    Type: AWS::ApiGateway::RequestValidator
    Properties:
      RestApiId: !ImportValue RestApiId
      Name: ValidateQueryString
      ValidateRequestParameters: true
      ValidateRequestBody: false 
  ApiGatewayRequestBodyValidator:
    Type: AWS::ApiGateway::RequestValidator
    Properties:
      RestApiId: !ImportValue RestApiId
      Name: ValidateRequestBody
      ValidateRequestParameters: false
      ValidateRequestBody: true
  
  ApiGatewayResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !ImportValue RestApiRootResourceId
      RestApiId: !ImportValue RestApiId
      PathPart: !Ref EndPoint
  ApiGatewayStateResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref ApiGatewayResource
      RestApiId: !ImportValue RestApiId
      PathPart: state
  
  GetHelloNghiemStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${S3BucketName}.s3.amazonaws.com/${InfrastructureName}/templates/api-gateways/hello-nghiem/GET/template.yml
      TimeoutInMinutes: 20
      Parameters:
        CommitMessage: !Ref CommitMessage
        EndPoint: hello-nghiem
        InfrastructureName: !Ref InfrastructureName
        EnvironmentType: !Ref EnvironmentType
        MethodAPI: get
        ApiGatewayResourceId: !Ref ApiGatewayResource
        ApiGatewayRequestValidator: !Ref ApiGatewayRequestQueryStringValidator
  PostHelloNghiemStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: GetHelloNghiemStack
    Properties:
      TemplateURL: !Sub https://${S3BucketName}.s3.amazonaws.com/${InfrastructureName}/templates/api-gateways/hello-nghiem/POST/template.yml
      TimeoutInMinutes: 20
      Parameters:
        CommitMessage: !Ref CommitMessage
        EndPoint: hello-nghiem
        InfrastructureName: !Ref InfrastructureName
        EnvironmentType: !Ref EnvironmentType
        MethodAPI: post
        ApiGatewayResourceId: !Ref ApiGatewayResource
        ApiGatewayRequestValidator: !Ref ApiGatewayRequestBodyValidator
  GetHelloNghiemStateStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: PostHelloNghiemStack
    Properties:
      TemplateURL: !Sub https://${S3BucketName}.s3.amazonaws.com/${InfrastructureName}/templates/api-gateways/hello-nghiem/state/GET/template.yml
      TimeoutInMinutes: 20
      Parameters:
        CommitMessage: !Ref CommitMessage
        EndPoint: hello-nghiem-state # this is name of function
        InfrastructureName: !Ref InfrastructureName
        EnvironmentType: !Ref EnvironmentType
        MethodAPI: get
        ApiGatewayResourceId: !Ref ApiGatewayStateResource # this is endpoint
        ApiGatewayRequestValidator: !Ref ApiGatewayRequestQueryStringValidator