Parameters:
  CommitMessage:
    Type: String
  EndPoint:
    Type: String
    Default: hello-nghiem
  InfrastructureName:
    Type: String
    Default: nx-vid
  EnvironmentType:
    Description: Specify the Environment type of the stack.
    Type: String
    Default: test
    AllowedValues:
      - dev
      - test
      - prod
    ConstraintDescription: Specify either dev, test or prod.
  S3BucketName:
    Type: String
    Default: my-bucket-bucket

Resources:
  ApiGatewayResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !ImportValue RestApiRootResourceId
      RestApiId: !ImportValue RestApiId
      PathPart: !Ref EndPoint
  GetHelloNghiemStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${S3BucketName}.s3.amazonaws.com/${InfrastructureName}/templates/api-gateways/hello-nghiem/GET/template.yml
      TimeoutInMinutes: 20
      Parameters:
        CommitMessage: !Ref CommitMessage
        EndPoint: hello-nghiem
        InfrastructureName: !Ref InfrastructureName
        EnvironmentType: !Ref EnvironmentType
        MethodAPI: get
        ApiGatewayResourceId: !Ref ApiGatewayResource
  PostHelloNghiemStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: GetHelloNghiemStack
    Properties:
      TemplateURL: !Sub https://${S3BucketName}.s3.amazonaws.com/${InfrastructureName}/templates/api-gateways/hello-nghiem/POST/template.yml
      TimeoutInMinutes: 20
      Parameters:
        CommitMessage: !Ref CommitMessage
        EndPoint: hello-nghiem
        InfrastructureName: !Ref InfrastructureName
        EnvironmentType: !Ref EnvironmentType
        MethodAPI: post
        ApiGatewayResourceId: !Ref ApiGatewayResource 