AWSTemplateFormatVersion: "2010-09-09"

Description: API Gateway configuration for the Lambda function integrated with the layer.

Parameters:
  EndPoint:
    Type: String
    Default: hello-nghiem
  MethodAPI:
    Type: String
    Default: get
  InfrastructureName:
    Type: String
    Default: nx-vid
  EnvironmentType:
    Description: Specify the Environment type of the stack.
    Type: String
    Default: test
    AllowedValues:
      - dev
      - test
      - prod
    ConstraintDescription: Specify either dev, test or prod.

Mappings:
  UpperCaseMethodAPI:
    get:
      Method: GET
    post:
      Method: POST
    put:
      Method: PUT
    delete:
      Method: DELETE

Resources:
  ApiGatewayResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !ImportValue RestApiRootResourceId
      RestApiId: !ImportValue RestApiId
      PathPart: !Ref EndPoint

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${InfrastructureName}-${MethodAPI}-${EndPoint}
      Handler: lambda_function.handler
      Role: !ImportValue LambdaExecutionRole
      Code:
        S3Bucket: my-bucket-bucket
        S3Key: lambda-functions/get-hello-nghiem.zip
      Runtime: python3.12
      Environment:
        Variables:
          ENV_TYPE: !Ref EnvironmentType
      Layers:
        - !ImportValue pandas-layer
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt LambdaFunction.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: 
        Fn::Sub: 
          -  arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RestApiId}/*/${MethodAPI}/${EndPoint}
          - RestApiId: !ImportValue RestApiId
          - MethodAPI: !FindInMap [UpperCaseMethodAPI, !Ref MethodAPI, Method]

  ApiGatewayMethod:
    Type: AWS::ApiGateway::Method
    DependsOn: LambdaFunction
    Properties:
      HttpMethod: !FindInMap [UpperCaseMethodAPI, !Ref MethodAPI, Method]
      ResourceId: !Ref ApiGatewayResource
      RestApiId: !ImportValue RestApiId
      AuthorizationType: NONE
      Integration:
        Type: AWS
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaFunction.Arn}/invocations
      MethodResponses:
        - StatusCode: 200

  # ApiGatewayDeployment:
  #   Type: AWS::ApiGateway::Deployment
  #   DependsOn: ApiGatewayMethod
  #   Properties:
  #     RestApiId: !ImportValue RestApiId
  #     StageName: !Ref EnvironmentType

# Outputs:
#   ApiGatewayUrl:
#     Description: URL of the API Gateway
#     Value: !Sub https://${RestApiId}.execute-api.${AWS::Region}.amazonaws.com/${EnvironmentType}/${EndPoint} 