AWSTemplateFormatVersion: "2010-09-09"

Description: AWS CloudFormation template for Lambda Layer.

Resources:
  LambdaLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: pandas-layer
      Description: Lambda Layer for shared dependencies
      Content:
        S3Bucket: my-bucket-bucket
        S3Key: layers/pandas-layer.zip
      CompatibleRuntimes:
        - python3.12

Outputs:
  LayerVersionArn:
    Description: ARN of the Lambda Layer
    Value: !Ref LambdaLayer
    Export:
      Name: pandas-layer