Parameters:
  CommitMessage:
    Type: String
  EndPoint:
    Type: String
    Default: hello-nghiem
  InfrastructureName:
    Type: String
    Default: nx-vid
  EnvironmentType:
    Description: Specify the Environment type of the stack.
    Type: String
    Default: test
    AllowedValues:
      - dev
      - test
      - prod
    ConstraintDescription: Specify either dev, test or prod.
  S3BucketName:
    Type: String
    Default: my-bucket-bucket

Resources:
  ApiGatewayResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !ImportValue
        Fn::Sub: RestApiRootResourceId # Corrected syntax
      RestApiId: !ImportValue
        Fn::Sub: RestApiId             # Corrected syntax
      PathPart: !Ref EndPoint

  ApiGatewayTypeResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref ApiGatewayResource
      RestApiId: !ImportValue
        Fn::Sub: RestApiId             # Corrected syntax
      PathPart: "{type}"

Outputs:
  ApiGatewayResource:
    Value: !Ref ApiGatewayResource
    Export:
      Name: ApiGatewayHelloWorldResource
  ApiGatewayTypeResource:
    Value: !Ref ApiGatewayTypeResource
    Export:
      Name: ApiGatewayHelloWorldTypeResource