Parameters:
  CommitMessage:
    Type: String
  EndPoint:
    Type: String
    Default: hello-nghiem
  InfrastructureName:
    Type: String
    Default: nx-vid
  EnvironmentType:
    Description: Specify the Environment type of the stack.
    Type: String
    Default: test
    AllowedValues:
      - dev
      - test
      - prod
    ConstraintDescription: Specify either dev, test or prod.
  S3BucketName:
    Type: String
    Default: my-bucket-bucket

Resources:
  ApiGatewayResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !ImportValue RestApiRootResourceId-${EnvironmentType}
      RestApiId: !ImportValue RestApiId-${EnvironmentType}
      PathPart: !Ref EndPoint
  ApiGatewayTypeResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref ApiGatewayResource
      RestApiId: !ImportValue RestApiId-${EnvironmentType}
      PathPart: "{type}"
  
  GetHelloWorldStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${S3BucketName}.s3.amazonaws.com/${InfrastructureName}/templates/api-gateways/${EndPoint}/GET/template.yml
      TimeoutInMinutes: 20
      Parameters:
        CommitMessage: !Ref CommitMessage
        EndPoint: !Ref EndPoint
        LambdaFunctionFileName: !Ref EndPoint
        InfrastructureName: !Ref InfrastructureName
        EnvironmentType: !Ref EnvironmentType
        MethodAPI: get
        ApiGatewayResourceId: !Ref ApiGatewayResource
        ApiGatewayRequestValidator: !ImportValue ApiGatewayRequestQueryStringValidator-${EnvironmentType}
  GetTypeParameterStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${S3BucketName}.s3.amazonaws.com/${InfrastructureName}/templates/api-gateways/${EndPoint}/type/GET/template.yml
      TimeoutInMinutes: 20
      Parameters:
        CommitMessage: !Ref CommitMessage
        EndPoint: !Sub ${EndPoint}/{type}
        LambdaFunctionFileName: !Sub ${EndPoint}-type
        InfrastructureName: !Ref InfrastructureName
        EnvironmentType: !Ref EnvironmentType
        MethodAPI: get
        ApiGatewayResourceId: !Ref ApiGatewayTypeResource
        ApiGatewayRequestValidator: !ImportValue ApiGatewayRequestQueryStringValidator-${EnvironmentType}

  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: 
      - GetHelloWorldStack
      - GetTypeParameterStack
    Properties:
      RestApiId: !ImportValue RestApiId-${EnvironmentType}
      StageName: !Ref EnvironmentType
      Description: !Ref CommitMessage 