AWSTemplateFormatVersion: "2010-09-09"

Description: trigger lambda function from sqs.

Parameters:
  CommitMessage:
    Type: String
  LambdaFunctionFileName:
    Type: String
  InfrastructureName:
    Type: String
    Default: nx-vid
  EnvironmentType:
    Description: Specify the Environment type of the stack.
    Type: String
    Default: test
    AllowedValues:
      - dev
      - test
      - prod
    ConstraintDescription: Specify either dev, test or prod.

Resources:
  LambdaVersion:
    Type: AWS::Lambda::Version
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      FunctionName: !Sub ${InfrastructureName}-${LambdaFunctionFileName}
      Description: !Ref CommitMessage
  LambdaAlias:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !Sub ${InfrastructureName}-${LambdaFunctionFileName}
      FunctionVersion: !GetAtt LambdaVersion.Version
      Name: !Ref EnvironmentType
      Description: !Ref CommitMessage
      
