AWSTemplateFormatVersion: "2010-09-09"

Description: trigger lambda function from sqs.

Parameters:
  CommitMessage:
    Type: String
  LambdaFunctionFileName:
    Type: String
  InfrastructureName:
    Type: String
    Default: nx-vid
  EnvironmentType:
    Description: Specify the Environment type of the stack.
    Type: String
    Default: test
    AllowedValues:
      - dev
      - test
      - prod
    ConstraintDescription: Specify either dev, test or prod.

Resources:
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${InfrastructureName}-${LambdaFunctionFileName}
      Handler: lambda_function.handler
      Role: !ImportValue LambdaExecutionRole
      Code:
        S3Bucket: my-bucket-bucket
        S3Key:  !Sub lambda-functions/${LambdaFunctionFileName}-|COMMIT_HASH|.zip
      Runtime: python3.12
      Environment:
        Variables:
          ENV_TYPE: !Ref EnvironmentType