AWSTemplateFormatVersion: "2010-09-09"

Description: VID Api Gateway
Parameters:
  InfrastructureName:
    Type: String
    Default: nx-vid
  EnvironmentType:
    Description: Specify the Environment type of the stack.
    Type: String
    Default: test
    AllowedValues:
      - dev
      - test
      - prod
    ConstraintDescription: Specify either dev, test or prod.

Resources:
  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    DeletionPolicy: Retain
    Properties:
      Name: !Sub ${InfrastructureName}-api
      Description: API Gateway for Lambda function
Outputs:
  RestApiId:
    Value: !Ref ApiGateway
    Export:
      Name: RestApiId
  RestApiRootResourceId:
    Value: !GetAtt ApiGateway.RootResourceId
    Export:
      Name: RestApiRootResourceId