AWSTemplateFormatVersion: "2010-09-09"

Description: VID Infrastructure
Parameters:
  InfrastructureName:
    Type: String
    Default: nx-vid
  EnvironmentType:
    Description: Specify the Environment type of the stack.
    Type: String
    Default: test
    AllowedValues:
      - dev
      - test
      - prod
    ConstraintDescription: Specify either dev, test or prod.

Resources:
  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub ${InfrastructureName}-api
      Description: API Gateway for Lambda function
  
  # should be in infrastructure template    
  ApiGatewayRequestQueryStringValidator:
    Type: AWS::ApiGateway::RequestValidator
    Properties:
      RestApiId: !Ref ApiGateway
      Name: ValidateQueryString
      ValidateRequestParameters: true
      ValidateRequestBody: false 
  ApiGatewayRequestBodyValidator:
    Type: AWS::ApiGateway::RequestValidator
    Properties:
      RestApiId: !Ref ApiGateway
      Name: ValidateRequestBody
      ValidateRequestParameters: false
      ValidateRequestBody: true
  

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement: 
          - Effect: "Allow"
            Principal: 
              Service: 
                - "lambda.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Policies: 
        - PolicyName: "LambdaExecutionPolicy"
          PolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - Effect: "Allow"
                Action: 
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "*"
                
Outputs:
  ApiGatewayRequestQueryStringValidator:
    Value: !Ref ApiGatewayRequestQueryStringValidator
    Export:
      Name: ApiGatewayRequestQueryStringValidator-${EnvironmentType}
  ApiGatewayRequestBodyValidator:
    Value: !Ref ApiGatewayRequestBodyValidator
    Export:
      Name: ApiGatewayRequestBodyValidator-${EnvironmentType}
  RestApiId${EnvironmentType}:
    Value: !Ref ApiGateway
    Export:
      Name: RestApiId-${EnvironmentType}
  RestApiRootResourceId:
    Value: !GetAtt ApiGateway.RootResourceId
    Export:
      Name: RestApiRootResourceId-${EnvironmentType}
  LambdaExecutionRole:
    Value: !GetAtt LambdaExecutionRole.Arn
    Export:
      Name: LambdaExecutionRole-${EnvironmentType}
  InfrastructureName:
    Value: !Ref InfrastructureName
    Export:
      Name: InfrastructureName-${EnvironmentType}