AWSTemplateFormatVersion: "2010-09-09"

Description: VID Infrastructure
Parameters:
  InfrastructureName:
    Type: String
    Default: nx-vid
  EnvironmentType:
    Description: Specify the Environment type of the stack.
    Type: String
    Default: test
    AllowedValues:
      - dev
      - test
      - prod
    ConstraintDescription: Specify either dev, test or prod.

Resources:
  # Adding an SQS Queue
  ProcessingQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${InfrastructureName}-queue-${EnvironmentType}
      VisibilityTimeout: 300
      MessageRetentionPeriod: 345600 # 4 days
      DelaySeconds: 0
      # Optional: Configure dead-letter queue if needed
      # RedrivePolicy:
      #   deadLetterTargetArn: !GetAtt DeadLetterQueue.Arn
      #   maxReceiveCount: 5
      Tags:
        - Key: Name
          Value: !Sub ${InfrastructureName}-queue-${EnvironmentType}
        - Key: Environment
          Value: !Ref EnvironmentType
           
Outputs:
  InfrastructureName:
    Value: !Ref InfrastructureName
    Export:
      Name: !Sub InfrastructureName-${EnvironmentType}
  ProcessingQueue:
    Value: !GetAtt ProcessingQueue.Arn
    Export:
      Name: !Sub ProcessingQueue-${EnvironmentType}