AWSTemplateFormatVersion: "2010-09-09"

Description: VID Infrastructure
Parameters:
  InfrastructureName:
    Type: String
    Default: nx-vid
  EnvironmentType:
    Description: Specify the Environment type of the stack.
    Type: String
    Default: test
    AllowedValues:
      - dev
      - test
      - prod
    ConstraintDescription: Specify either dev, test or prod.

Resources:
  # Adding an SQS FIFO Queue
  ProcessingQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${InfrastructureName}-queue-${EnvironmentType}.fifo
      FifoQueue: true
      ContentBasedDeduplication: true
      VisibilityTimeout: 300
      MessageRetentionPeriod: 345600 # 4 days
      DelaySeconds: 5 # Adding a delay of 5 seconds to the queue
      Tags:
        - Key: Name
          Value: !Sub ${InfrastructureName}-queue-${EnvironmentType}.fifo
        - Key: Environment
          Value: !Ref EnvironmentType
           
Outputs:
  InfrastructureName:
    Value: !Ref InfrastructureName
    Export:
      Name: !Sub InfrastructureName-${EnvironmentType}
  ProcessingQueue:
    Value: !GetAtt ProcessingQueue.Arn
    Export:
      Name: !Sub ProcessingQueue-${EnvironmentType}