AWSTemplateFormatVersion: "2010-09-09"

Description: API Gateway configuration for the Lambda function integrated with the layer.

Parameters:
  CommitMessage:
    Type: String
  LambdaFunctionFileName:
    Type: String
  MethodAPI:
    Type: String
    Default: get
  InfrastructureName:
    Type: String
    Default: nx-vid
  EnvironmentType:
    Description: Specify the Environment type of the stack.
    Type: String
    Default: test
    AllowedValues:
      - dev
      - test
      - prod
    ConstraintDescription: Specify either dev, test or prod.

Mappings:
  UpperCaseMethodAPI:
    get:
      Method: GET
    post:
      Method: POST
    put:
      Method: PUT
    delete:
      Method: DELETE

Resources:
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${InfrastructureName}-${MethodAPI}-${LambdaFunctionFileName}
      Handler: lambda_function.handler
      Role: !ImportValue
        Fn::Sub: LambdaExecutionRole
      Code:
        S3Bucket: my-bucket-bucket
        S3Key: !Sub lambda-functions/${MethodAPI}-${LambdaFunctionFileName}-|COMMIT_HASH|.zip
      Runtime: python3.12
      Environment:
        Variables:
          ENV_TYPE: !Ref EnvironmentType
      Layers:
        - !ImportValue numpy-layer

  ApiGatewayMethod:
    Type: AWS::ApiGateway::Method
    DependsOn: LambdaFunction
    Properties:
      HttpMethod: !FindInMap [UpperCaseMethodAPI, !Ref MethodAPI, Method]
      ResourceId: !ImportValue ApiGatewayHelloWorldTypeResource
      RestApiId: !ImportValue
        Fn::Sub: RestApiId
      AuthorizationType: NONE
      RequestValidatorId: !ImportValue ApiGatewayRequestQueryStringValidator
      RequestParameters:
        method.request.path.type: true
      Integration:
        Type: AWS
        IntegrationHttpMethod: POST    
        Uri: !Join
          - ""
          - - !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaFunction.Arn}
            - ":${stageVariables.env}/invocations"
        IntegrationResponses:
          - StatusCode: 200
            ResponseTemplates:
              application/json: ""
      MethodResponses:
      - StatusCode: 200
        ResponseModels:
          application/json: Empty