name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - test
env:
  COMMIT_HASH: ${{ github.sha }}
  BRANCH_NAME: ${{ github.ref_name }}
  COMMIT_MESSAGE: ${{ github.event.head_commit.message }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.MY_AWS_REGION }}
      - name: Debug file path
        run: |
          ls -la
          echo $COMMIT_MESSAGE
          echo $BRANCH_NAME

      - name: Package and upload Lambda layers
        run: |
          chmod +x ./templates/bash_scripts/prepare_layers.sh
          ./templates/bash_scripts/prepare_layers.sh

      - name: Package Lambda function
        run: |
          chmod +x ./templates/bash_scripts/prepare_lambda.sh
          ./templates/bash_scripts/prepare_lambda.sh
      - name: Upload Template files
        run: |
          chmod +x ./templates/bash_scripts/prepare_templates.sh
          ./templates/bash_scripts/prepare_templates.sh

  deploy:
      runs-on: ubuntu-latest
      needs: build

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up AWS CLI
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.MY_AWS_REGION }}

        - name: Deploy Infrastructure Stack
          run: |
            echo "Deploying main infrastructure stack..."
            aws cloudformation deploy \
              --template-file templates/infrastructure/template.yml \
              --stack-name nx-vid-infrastructure-stack \
              --parameter-overrides EnvironmentType="${{ env.BRANCH_NAME }}" \
              --capabilities CAPABILITY_IAM
        - name: Deploy Layers
          run: |
            chmod +x ./templates/bash_scripts/deploy_layers.sh
            ./templates/bash_scripts/deploy_layers.sh
        - name: Deploy API Gateway
          run: |
            chmod +x ./templates/bash_scripts/deploy_apigateways.sh
            ./templates/bash_scripts/deploy_apigateways.sh