name: Deploy-Infrastructure

on:
  workflow_run:
      workflows: ['Deploy-Layer']
      types: [completed]
  push:
    paths:
      - templates/infrastructure/**/*
    branches:
      - dev
      - test
env:
  COMMIT_HASH: ${{ github.sha }}
  BRANCH_NAME: ${{ github.ref_name }}
  COMMIT_MESSAGE: ${{ github.event.head_commit.message }}

jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up AWS CLI
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.MY_AWS_REGION }}

        - name: Deploy Roles stack
          run: |
            echo "Deploying roles stack..."
            aws cloudformation deploy \
              --template-file templates/infrastructure/role.yml \
              --stack-name nx-vid-roles-stack \
              --capabilities CAPABILITY_IAM

        - name: Deploy Infrastructure Stack
          run: |
            echo "Deploying main infrastructure stack..."
            aws cloudformation deploy \
              --template-file templates/infrastructure/template.yml \
              --stack-name nx-vid-infrastructure-${{ env.BRANCH_NAME }}-stack \
              --parameter-overrides EnvironmentType="${{ env.BRANCH_NAME }}" \
              --capabilities CAPABILITY_IAM
        
        - name: Deploy api gateway
          run: |
            echo "Deploying API Gateway stack..."
            aws cloudformation deploy \
              --template-file templates/infrastructure/api-gateway.yml \
              --stack-name nx-vid-api-gateway-stack \
              --parameter-overrides EnvironmentType="${{ env.BRANCH_NAME }}" \
              --capabilities CAPABILITY_IAM