name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.MY_AWS_REGION }}
      - name: Debug file path
        run: ls -la

      - name: Package and upload Lambda layers
        run: |
          chmod +x ./templates/bash_scripts/prepare_layers.sh
          ./templates/bash_scripts/prepare_layers.sh

      # - name: Package Lambda function
      #   run: |
      #     cd src/lambda_function
      #     zip -r function.zip .
      #     aws s3 cp function.zip s3://your-s3-bucket-name/templates/

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #     - name: Deploy CloudFormation stacks
  #       run: |
  #         aws cloudformation deploy --template-file templates/main.yml --stack-name my-main-stack --capabilities CAPABILITY_IAM