name: ecs-fibonaci-td-pipeline
# This workflow is triggered when there are changes in the hello-world folder
on:
  workflow_run:
      workflows: ['Deploy-Infrastructure']
      types: [completed]
  push:
    paths:
      - templates/fargate/fibonaci/**/*
    branches:
      - dev
      - test
env:
  COMMIT_HASH: ${{ github.sha }}
  BRANCH_NAME: ${{ github.ref_name }}
  COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
  DOCKER_USER_NAME: meonghiem
  DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  FOLDER_NAME: templates/fargate/fibonaci

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.MY_AWS_REGION }}

      - name: Package Docker image
        run: |
          chmod +x ./templates/bash_scripts/prepare_docker.sh
          ./templates/bash_scripts/prepare_docker.sh $FOLDER_NAME

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.MY_AWS_REGION }}

      - name: Deploy ECS Task Definition
        run: |
            chmod +x ./templates/bash_scripts/deploy_fargate.sh
            ./templates/bash_scripts/deploy_fargate.sh $FOLDER_NAME

  
      