name: API Gateway pipeline for hello-nghiem endpoint
# This workflow is triggered when there are changes in the hello-nghiem folder

on:
  workflow_run:
      workflows: ['Deploy-Infrastructure']
      types: [completed]
  push:
    paths:
      - templates/api-gateways/hello-nghiem/**/*
    branches:
      - dev
      - test
env:
  COMMIT_HASH: ${{ github.sha }}
  BRANCH_NAME: ${{ github.ref_name }}
  COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
  FOLDER_NAME: hello-nghiem

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.MY_AWS_REGION }}
      - name: Debug file path
        run: |
          ls -la
          echo $COMMIT_MESSAGE
          echo $BRANCH_NAME

      - name: Package Lambda function
        run: |
          chmod +x ./templates/bash_scripts/prepare_lambda.sh
          ./templates/bash_scripts/prepare_lambda.sh $FOLDER_NAME

  deploy:
      runs-on: ubuntu-latest
      needs: build

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up AWS CLI
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.MY_AWS_REGION }}
            
        - name: Deploy Endpoint
          run: |
            chmod +x ./templates/bash_scripts/deploy_endpoint.sh
            ./templates/bash_scripts/deploy_endpoint.sh $FOLDER_NAME

        - name: Deploy API Gateway
          run: |
            chmod +x ./templates/bash_scripts/deploy_apigateways.sh
            ./templates/bash_scripts/deploy_apigateways.sh $FOLDER_NAME

        - name: Deploy Lambda alias integrated with API Gateway
          run: |
            chmod +x ./templates/bash_scripts/deploy_lambda_alias.sh
            ./templates/bash_scripts/deploy_lambda_alias.sh $FOLDER_NAME